#!/bin/sh -e
# vim:se sw=2 ts=2 sts=2 et ai tw=78:
#

git submodule update --init --recursive
git submodule foreach '\
git submodule foreach 'git config submodule.$name.update rebase'
git submodule foreach 'git config pull.rebase true'
git submodule foreach 'git remote set-url --push origin DISABLED_FOR_PUSH'
git submodule foreach 'git checkout master'
git config pull.rebase true

# I will push to vim-spell-under
(
  cd pack/gitsubmodules/opt/vim-spell-under ; \
  git remote set-url --delete --push origin DISABLED_FOR_PUSH \
)


